attention_dropout: 0.1
batch_size: 64
betas:
- 0.9
- 0.999
checkpoints_path: /home/zjy/uav1/saved_models/DT-UAV-fd9188e2
clip_grad: 0.25
dataset_path: /home/zjy/uav1/uav_combat_dataset.hdf5
deterministic_torch: false
device: cuda
embedding_dim: 128
embedding_dropout: 0.1
episode_len: 100
eval_episodes: 100
eval_every: 2000
eval_seed: 42
learning_rate: 0.0001
log_dir: runs
max_action: 1.0
num_heads: 1
num_layers: 3
num_workers: 4
residual_dropout: 0.1
reward_scale: 1
seq_len: 20
target_returns:
- 80.0
train_seed: 10
update_steps: 50000
warmup_steps: 5000
weight_decay: 0.0001
